// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQx-7ZGkxi08pNR4exenZEcn-zjBCtUco',
    appId: '1:626801727731:web:78e469f28cd128b3f03f86',
    messagingSenderId: '626801727731',
    projectId: 'books-course-work-1',
    authDomain: 'books-course-work-1.firebaseapp.com',
    storageBucket: 'books-course-work-1.appspot.com',
    measurementId: 'G-16HR47WC9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVrmV93zGY_JVACAME5lqEIrcoisN-mqM',
    appId: '1:626801727731:android:c4b239cf2cf5844cf03f86',
    messagingSenderId: '626801727731',
    projectId: 'books-course-work-1',
    storageBucket: 'books-course-work-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDXLswLpWWT7Bp4zvHkytsLha08BeMXI',
    appId: '1:626801727731:ios:9674c99377c62889f03f86',
    messagingSenderId: '626801727731',
    projectId: 'books-course-work-1',
    storageBucket: 'books-course-work-1.appspot.com',
    androidClientId: '626801727731-qk19if9unbqal9m7kopqmi89jcbque79.apps.googleusercontent.com',
    iosClientId: '626801727731-kbcte6jeoj3pl8pdb7kbm0b1j9sfl335.apps.googleusercontent.com',
    iosBundleId: 'com.example.adm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDXLswLpWWT7Bp4zvHkytsLha08BeMXI',
    appId: '1:626801727731:ios:9674c99377c62889f03f86',
    messagingSenderId: '626801727731',
    projectId: 'books-course-work-1',
    storageBucket: 'books-course-work-1.appspot.com',
    androidClientId: '626801727731-qk19if9unbqal9m7kopqmi89jcbque79.apps.googleusercontent.com',
    iosClientId: '626801727731-kbcte6jeoj3pl8pdb7kbm0b1j9sfl335.apps.googleusercontent.com',
    iosBundleId: 'com.example.adm',
  );
}
